exports.content = {
    cancel : "Cancel",
    error404 : "404! we can't find this page",
    readmore : "Read more &raquo;",
    
    pagetitle_homepage : "Homepage",
    pagetitle_aboutme : "About",
    pagetitle_updatepost : "Update Post",
    pagetitle_trash : "Blog Trash Can",
    pagetitle_password : "Change Password",
    pagetitle_404 : "Error 404",

    nav_blog : "Blog",
    nav_aboutme: "About me",
    nav_admin_login: "Admin login",
    nav_admin: "Admin",
    nav_admin_setting: "Setting",
    nav_admin_data : "Data Center",
    nav_admin_addpost: "Add Post",
    nav_admin_myposts: "My Posts",
    nav_admin_password: "Password",
    nav_admin_logout: "Logout",

    page_older : "Older posts →",
    page_newer : "← Newer posts",

    relevant_tags: "Tags",
    relevant_links: "Links",
    relevant_meweb: "Me & Web",

    login_username: "Username",
    login_password: "Password",
    login_submit: "Login",
    login_failed: "Username or password is incorrect!",

    tip_nopost: "Well done! Let's going to write your first article: ",
    tip_noaboutme: "This is the default about content, you can create your own about content under Admin->Setting page after logged in.",

    setting_lang: "Lang",
    setting_lang_tip: "Site language setting, node.js service restart required",
    setting_sitename: "Site Name",
    setting_sitename_tip: "Site name, as well as HTML title",
    setting_sitedesc: "Site Desc",
    setting_sitedesc_tip: "HTML description meta tag value",
    setting_keywords: "Keywords",
    setting_keywords_tip: "HTML keywords meta tag value",
    setting_commentservice: "Comment Service",
    setting_commentservice_tip: "We support <a href='http://disqus.com' target='_blank'>Disqus</a>, <a href='http://www.livefyre.com/' target='_blank'>Lifeflye</a> and <a href='http://duoshuo.com/' target='_blank'>duoshuo</a> currently, more Services coming soon",
    setting_commentserviceid: "Comment Service ID",
    setting_commentserviceid_tip: "The Unique ID from service above after sign up, such as shortname,siteId",
    setting_gaid: "Google Tracking ID",
    setting_gaid_tip: "The tracking ID of Google Analytics",
    setting_sitelogo: "Site Logo",
    setting_sitelogo_tip: "Top right image of the default theme",
    setting_footer: "Footer",
    setting_footer_tip: "Copyright text and so on",
    setting_aboutme: "About Me",
    setting_aboutme_tip: "Content of about me page",
    setting_links: "Links",
    setting_links_tip: "Friend's links, one link per line, use pipe symbol to separate link name and link address",
    setting_meweb: "Me & Web",
    setting_meweb_tip: "Your links on the web, one link per line, use pipe symbol to separate link name and link address",
    setting_submit: "Submit",
   
    post_title: "Title",
    post_tags: "Tags",
    post_tags_tip: "Seprated by comma or semi-colon or space",
    post_content: "Content",
    post_content_tip: "Support all markdown syntax include table",
    post_created: "Created Date",
    post_created_tip: "Leave this empty to use current datetime",
    post_submit: "Submit",

    mypost_admin: "Post Admin",
    mypost_trash: "Trash List",
    mypost_th_id: "ID",
    mypost_th_title: "Title",
    mypost_th_created: "Created Date",
    mypost_th_actions: "Actions",
    mypost_action_update: "Update",
    mypost_action_trash: "Trash",
    mypost_action_remove: "Remove",
    mypost_action_restore: "Restore",
    mypost_trash_empty: "There is no post in your trash can",
    mypost_trash_tip: "Are u sure u want to move this post to trash?",
    mypost_remove_tip: "Are u sure u want to remove this post forever? It is not cancelable!",
    mypost_adminlink: "Admin",
    mypost_trashlink: "Trash",

    password_username: "Username",
    password_oldpassword: "Old Password",
    password_newpassword: "New Password",
    password_confirmpassword: "Confirm Password",
    password_submit: "Submit",
    password_failed_username: "Username is not wellformated",
    password_failed_oldpassword: "Old Password is incorrect",
    password_failed_newpassword: "New Password is not wellformated, at least 6 chars",
    password_failed_match: "New Password confirmation is not match",
    password_changed: "Password changed!",

    admindata_title : "Data Backup/Restore",
    admindata_backup : "Backup",
    admindata_backup_tip : "Click the following button to start backuping all your setting and posts:",
    admindata_restore : "Restore",
    admindata_restore_upload : "Please choose a backup zip file to restore:",
    admindata_restorefilenotfound : "The restore zip file --@1-- is not found",
    admindata_restore_file : "Data File to Restore:",
    admindata_restore_tip : "Caution, this action will replace all current data with the following zip data you have uploaded and can not be undone! Please make sure that you want to proceed !!",
    admindata_dorestore : "Proceed Restore",
    admindata_restore_succ : "Restore succeed"
};
